// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRyepCioXYplpLkHnGGtGsz0OzO0G6U-4',
    appId: '1:907958190887:android:4df482e637523e29e59f02',
    messagingSenderId: '907958190887',
    projectId: 'can-we-chat-29cc2',
    storageBucket: 'can-we-chat-29cc2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyByGmLqXdLF6Qc7b4hqMSNcjdK8hX8uYdE',
    appId: '1:907958190887:ios:366ef070491705b8e59f02',
    messagingSenderId: '907958190887',
    projectId: 'can-we-chat-29cc2',
    storageBucket: 'can-we-chat-29cc2.appspot.com',
    androidClientId: '907958190887-1lj45dqe7omnf6oi21e7ccuq7j2m01o3.apps.googleusercontent.com',
    iosClientId: '907958190887-n0b871uidmkrcfv2eg1e8i6ojvekdjdt.apps.googleusercontent.com',
    iosBundleId: 'com.example.canWeChat',
  );
}
